account_shop_project/urls.py
from django.urls import path
from . import views


app_name = "account_shop_project"

urlpatterns = [
    path('login/', views.LoginView.as_view(), name='login'),
    path('reset_password/', views.ResetPasswordView.as_view(), name='reset_password'),
    path('register/', views.RegisterView.as_view(), name='register'),
    path('activate_account/<email_active_code>', views.ActivateAccountView.as_view(), name='activate_account'),
    path('change_password/<str:active_code>', views.ChangePasswordView.as_view(), name='change_password'),
    path('factor/', views.Factor.as_view(), name='factor'),
    path('factor/<order_id>', views.factor_detail,name='factor_detail'),
    path('profile/', views.ProfileView.as_view(), name='profile'),
    path('user/api/',views.User_api.as_view(),name='user_api'),
    path('return/<order_id>/', views.Return, name='return'),
    path('logout/', views.custom_logout, name='logout')

]

blog/urls.py
from django.urls import path
from . import views

app_name = "blog"

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),

    path('rate/<int:product_id>/', views.rate_product, name='rate_product'),
    path('search/', views.product_search, name='search'),
    path('products/', views.ProductView.as_view(), name='products'),
    path('products/<int:product_id>/', views.ProductDetailView.as_view(), name='product-detail'),
    path('response-comment/', views.Response_CommentView.as_view(), name='response-comment'),
    path('product/api', views.Product_api.as_view(), name='product_api'),
    path('category/api', views.Category_api.as_view(), name='category_api'),
]

mive_bama/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.urls import path, re_path, include
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi

schema_view = get_schema_view(
    openapi.Info(
        title="MiveBama API",
        default_version='v1',
        description="api documention for mivebama",
        terms_of_service="https://www.yourapp.com/terms/",
        contact=openapi.Contact(email="contact@yourapp.com"),
        license=openapi.License(name="BSD License"),
    ),
    public=False,
    permission_classes=(permissions.IsAuthenticated,),
)

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('blog.urls', namespace='blog')),
                  path('user/', include('account_shop_project.urls', namespace='account_shop_project')),
                  path('Order/', include('Order.urls', namespace='order')),
                  path('comment/', include('comment.urls', namespace='comment')),
                  path('swagger/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
                  path('Panel/', include('admin.urls', namespace='panel')),
                  path('accounts', include('allauth.urls'))
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/change-password.html
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="rtl">
    <head>
        <!--=====================================
                    META TAG PART START
        =======================================-->
        <!-- REQUIRE META -->
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <!-- AUTHOR META -->
        <meta name="author" content="mironcoder">
        <meta name="email" content="mironcoder@gmail.com">
        <meta name="profile" content="https://themeforest.net/user/mironcoder">

        <!-- TEMPLATE META -->
        <meta name="name" content="Greeny">
        <meta name="title" content="Greeny - eCommerce HTML Template">
        <meta name="keywords" content="organic, food, shop, ecommerce, store, html, bootstrap, template, agriculture, vegetables, webshop, farm, grocery, natural, online store">
        <!--=====================================
                    META-TAG PART END
        =======================================-->

        <!-- WEBPAGE TITLE -->
        <title>Greeny - Change Password</title>

        <!--=====================================
                    CSS LINK PART START
        =======================================-->
        <!-- FAVICON -->
        <link rel="icon" href="{{ media_url }}images/favicon.png">

        <!-- FONTS -->
        <link rel="stylesheet" href="{% static 'fonts/flaticon/flaticon.css' %}">
        <link rel="stylesheet" href="{% static 'fonts/icofont/icofont.min.css' %}">
        <link rel="stylesheet" href="{% static 'fonts/fontawesome/fontawesome.min.css' %}">

        <!-- VENDOR -->
        <link rel="stylesheet" href="{% static 'vendor/venobox/venobox.min.css' %}">
        <link rel="stylesheet" href="{% static 'vendor/slickslider/slick.min.css' %}">
        <link rel="stylesheet" href="{% static 'vendor/niceselect/nice-select.min.css' %}">
        <link rel="stylesheet" href="{% static 'vendor/bootstrap/bootstrap.min.css' %}">

        <!-- CUSTOM -->
        <link rel="stylesheet" href="{% static 'css/main.css' %}">
        <link rel="stylesheet" href="{% static 'css/user-auth.css' %}">
        <!--=====================================
                    CSS LINK PART END
        =======================================-->
    </head>
    <body>
        <!--=====================================
                    USER FORM PART START
        =======================================-->
        <section class="user-form-part">
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-12 col-sm-10 col-md-8 col-lg-6 col-xl-5">
                        <div class="user-form-logo">
                            <a href="{% url 'blog:index' %}"><img src="{{ media_url }}images/logo.png" alt="logo"></a>
                        </div>
                        <div class="user-form-card">
                            <div class="user-form-title">
                                <h2>مشکلی دارید؟</h2>
                                <p>مطمئن شوید رمز عبور فعلی شما قوی است</p>
                            </div>
                            <form class="user-form" method="post" action="{% url 'blog:change_password' active_code=user.email_active_code %} ">
                                <div class="form-group">
                                   {{ form.password }}
                                </div>
                                <div class="form-group">
                                    {{ form.confirm_password }}
                                </div>
                                <div class="form-button">
                                    <button type="submit">تغییر پسوورد</button>
                                </div>
                            </form>
                        </div>
                        <div class="user-form-remind">
                            <p>برگشت به <a href="{% url 'account_shop_project:login' %}">صفحه لاگین</a></p>
                        </div>
                        <div class="user-form-footer">
                            <p>Greeny | &COPY; Copyright by <a href="#">mrzic</a></p>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <!--=====================================
                    USER FORM PART END
        =======================================-->


        <!--=====================================
                    JS LINK PART START
        =======================================-->
        <!-- VENDOR -->
        <script src="{% static 'vendor/bootstrap/jquery-1.12.4.min.js' %}"></script>
        <script src="{% static 'vendor/bootstrap/popper.min.js' %}"></script>
        <script src="{% static 'vendor/bootstrap/bootstrap.min.js' %}"></script>
        <script src="{% static 'vendor/countdown/countdown.min.js' %}"></script>
        <script src="{% static 'vendor/niceselect/nice-select.min.js' %}"></script>
        <script src="{% static 'vendor/slickslider/slick.min.js' %}"></script>
        <script src="{% static 'vendor/venobox/venobox.min.js' %}"></script>

        <!-- CUSTOM -->
        <script src="{% static 'js/nice-select.js' %}"></script>
        <script src="{% static 'js/countdown.js' %}"></script>
        <script src="{% static 'js/accordion.js' %}"></script>
        <script src="{% static 'js/venobox.js' %}"></script>
        <script src="{% static 'js/slick.js' %}"></script>
        <script src="{% static 'js/main.js' %}"></script> 
        <!--=====================================
                    JS LINK PART END
        =======================================-->
    </body>
</html>

templates/login.html
{% load static %}
{% load socialaccount %}
<!DOCTYPE html>
<html lang="en" dir="rtl">
<head>
    <!--=====================================
                META TAG PART START
    =======================================-->
    <!-- REQUIRE META -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- AUTHOR META -->
    <meta name="author" content="mironcoder">
    <meta name="email" content="mironcoder@gmail.com">
    <meta name="profile" content="https://themeforest.net/user/mironcoder">

    <!-- TEMPLATE META -->
    <meta name="name" content="Greeny">
    <meta name="title" content="Greeny - eCommerce HTML Template">
    <meta name="keywords"
          content="organic, food, shop, ecommerce, store, html, bootstrap, template, agriculture, vegetables, webshop, farm, grocery, natural, online store">
    <!--=====================================
                META-TAG PART END
    =======================================-->

    <!-- WEBPAGE TITLE -->
    <title>Greeny - Login</title>

    <!--=====================================
                CSS LINK PART START
    =======================================-->
    <!-- FAVICON -->
    <link rel="icon" href="{{ media_url }}images/favicon.png">

    <!-- FONTS -->
    <link rel="stylesheet" href="{% static 'fonts/flaticon/flaticon.css' %}">
    <link rel="stylesheet" href="{% static 'fonts/icofont/icofont.min.css' %}">
    <link rel="stylesheet" href="{% static 'fonts/fontawesome/fontawesome.min.css' %}">

    <!-- VENDOR -->
    <link rel="stylesheet" href="{% static 'vendor/venobox/venobox.min.css' %}">
    <link rel="stylesheet" href="{% static 'vendor/slickslider/slick.min.css' %}">
    <link rel="stylesheet" href="{% static 'vendor/niceselect/nice-select.min.css' %}">
    <link rel="stylesheet" href="{% static 'vendor/bootstrap/bootstrap.min.css' %}">

    <!-- CUSTOM -->
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <link rel="stylesheet" href="{% static 'css/user-auth.css' %}">
    <!--=====================================
                CSS LINK PART END
    =======================================-->
</head>
<body>
<!--=====================================
            USER FORM PART START
=======================================-->
<section class="user-form-part">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-sm-10 col-md-12 col-lg-12 col-xl-10">
                
                <div class="user-form-card">
                    <div class="user-form-title">
                        <h2>خوش آمدید!</h2>
                        <p>عضو گرینی هستید؟با اطلاعات خود وارد شوید.</p>
                    </div>
                    <div class="user-form-group">


                        <form class="user-form" method="post" action="{% url 'account_shop_project:login' %}">
                            {% csrf_token %}
                            <div class="form-group">
                                {{ form.email }}
                            </div>
                            <div class="form-group">
                                {{ form.password }}
                            </div>
                            <div class="form-check mb-3">
                                <input class="form-check-input" type="checkbox" value="" id="check">
                                <label class="form-check-label" for="check">مرا به خاطر بسپار</label>
                            </div>
                            <div class="form-button">
                                <button type="submit"><a href="{% url 'blog:index' %}">ورود</a></button>
                                <p>پسوورد خود را فراموش کردید؟<a href="{% url 'account_shop_project:reset_password' %}">بازیابی
                                    پسوورد</a></p>
                            </div>
                        </form>
                    </div>
                </div>
                <div class="user-form-remind">
                    <p>هیچ حساب کاربری ندارید؟<a href="{% url 'account_shop_project:register' %}">ثبت نام کنید</a></p>

                </div>
                <div class="user-form-footer">
                    <p>ساخته شده توسط محمد رضا اخلاقی</p>
                </div>
            </div>
        </div>
    </div>
</section>
<!--=====================================
            USER FORM PART END
=======================================-->


<!--=====================================
            JS LINK PART START
=======================================-->
<!-- VENDOR -->
<script src="{% static 'vendor/bootstrap/jquery-1.12.4.min.js' %}"></script>
<script src="{% static 'vendor/bootstrap/popper.min.js' %}"></script>
<script src="{% static 'vendor/bootstrap/bootstrap.min.js' %}"></script>
<script src="{% static 'vendor/countdown/countdown.min.js' %}"></script>
<script src="{% static 'vendor/niceselect/nice-select.min.js' %}"></script>
<script src="{% static 'vendor/slickslider/slick.min.js' %}"></script>
<script src="{% static 'vendor/venobox/venobox.min.js' %}"></script>

<!-- CUSTOM -->
<script src="{% static 'js/nice-select.js' %}"></script>
<script src="{% static 'js/countdown.js' %}"></script>
<script src="{% static 'js/accordion.js' %}"></script>
<script src="{% static 'js/venobox.js' %}"></script>
<script src="{% static 'js/slick.js' %}"></script>
<script src="{% static 'js/main.js' %}"></script>
<!--=====================================
            JS LINK PART END
=======================================-->
</body>
</html>

templates/payment_result.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<div class="container">
    <div class="row">
        <div class="col-md-12">
            {% if info %}
                <div class="alert alert-info">
                    {{ info }}
                </div>
            {% endif %}
            {% if error %}
                <div class="alert alert-info">
                    {{ error }}
                </div>
            {% endif %}
            {% if success %}
                <div class="alert alert-info">
                    {{ success }}
                </div>
            {% endif %}
        </div>
        <p><a href="{% url 'blog:index' %}" class="btn">بازگشت به خانه</a></p>
    </div>
</div>
</body>
</html>

templates/rate_product.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>امتیاز دهی به محصول ({{ product.title }})</h1>
  <form method="post" action="{% url 'blog:rate_product' product.id %}">
     <h2>امتیاز خود را به این محصول از بین 1 تا 5 بدهید</h2>
    {% csrf_token %}
    {{ form }}
    <button type="submit">ثبت امتیاز</button>
  </form>
</body>
</html>

templates/register.html
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="rtl">
    <head>
        <!--=====================================
                    META TAG PART START
        =======================================-->
        <!-- REQUIRE META -->
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <!-- AUTHOR META -->
        <meta name="author" content="mironcoder">
        <meta name="email" content="mironcoder@gmail.com">
        <meta name="profile" content="https://themeforest.net/user/mironcoder">

        <!-- TEMPLATE META -->
        <meta name="name" content="Greeny">
        <meta name="title" content="Greeny - eCommerce HTML Template">
        <meta name="keywords" content="organic, food, shop, ecommerce, store, html, bootstrap, template, agriculture, vegetables, webshop, farm, grocery, natural, online store">
        <!--=====================================
                    META-TAG PART END
        =======================================-->

        <!-- WEBPAGE TITLE -->
        <title>Greeny - Register</title>

        <!--=====================================
                    CSS LINK PART START
        =======================================-->
        <!-- FAVICON -->
        <link rel="icon" href="{{ media_url }}images/favicon.png">

        <!-- FONTS -->
        <link rel="stylesheet" href="{% static 'fonts/flaticon/flaticon.css' %}">
        <link rel="stylesheet" href="{% static 'fonts/icofont/icofont.min.css' %}">
        <link rel="stylesheet" href="{% static 'fonts/fontawesome/fontawesome.min.css' %}">

        <!-- VENDOR -->
        <link rel="stylesheet" href="{% static 'vendor/venobox/venobox.min.css' %}">
        <link rel="stylesheet" href="{% static 'vendor/slickslider/slick.min.css' %}">
        <link rel="stylesheet" href="{% static 'vendor/niceselect/nice-select.min.css' %}">
        <link rel="stylesheet" href="{% static 'vendor/bootstrap/bootstrap.min.css' %}">

        <!-- CUSTOM -->
        <link rel="stylesheet" href="{% static 'css/main.css' %}">
        <link rel="stylesheet" href="{% static 'css/user-auth.css' %}">
        <!--=====================================
                    CSS LINK PART END
        =======================================-->
    </head>
    <body>
        <!--=====================================
                    USER FORM PART START
        =======================================-->
        <section class="user-form-part">
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-12 col-sm-10 col-md-12 col-lg-12 col-xl-10">
                        <div class="user-form-logo">
                            
                        </div>
                        <div class="user-form-card">
                            <div class="user-form-title">
                                <h2>عضو خانواده بزرگ گرینی شوید!</h2>
                                <p>ثبت نام شما تنها چند دقیقه زمان می برد.</p>
                            </div>
                            <div class="user-form-group">
                                <form class="user-form" action="{% url 'account_shop_project:register' %}" method="post">
                                    {% csrf_token %}
                                    <div class="form-group">
                                        {{ form.username }}
                                    </div>
                                    <div class="form-group">
                                          {{ form.email }}
                                    </div>
                                    <div class="form-group">
                                        {{ form.password }}
                                    </div>
                                    <div class="form-group">
                                        {{ form.confirm_password }}
                                    </div>
                                    {{ form.errors }}
                                    
                                    <div class="form-button">
                                        <button type="submit">ثبت نام</button>
                                    </div>
                                </form>
                            </div>
                        </div>
                        <div class="user-form-remind">
                            <p>از قبل عضو هستید؟<a href="{% url 'account_shop_project:login' %}">وارد شوید</a></p>
                        </div>
                        <div class="user-form-footer">
                            <p>ساخته شده توسط محمد رضا اخلاقی</p>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <!--=====================================
                    USER FORM PART END
        =======================================-->


        <!--=====================================
                    JS LINK PART START
        =======================================-->
        <!-- VENDOR -->
        <script src="{% static 'vendor/bootstrap/jquery-1.12.4.min.js' %}"></script>
        <script src="{% static 'vendor/bootstrap/popper.min.js' %}"></script>
        <script src="{% static 'vendor/bootstrap/bootstrap.min.js' %}"></script>
        <script src="{% static 'vendor/countdown/countdown.min.js' %}"></script>
        <script src="{% static 'vendor/niceselect/nice-select.min.js' %}"></script>
        <script src="{% static 'vendor/slickslider/slick.min.js' %}"></script>
        <script src="{% static 'vendor/venobox/venobox.min.js' %}"></script>

        <!-- CUSTOM -->
        <script src="{% static 'js/nice-select.js' %}"></script>
        <script src="{% static 'js/countdown.js' %}"></script>
        <script src="{% static 'js/accordion.js' %}"></script>
        <script src="{% static 'js/venobox.js' %}"></script>
        <script src="{% static 'js/slick.js' %}"></script>
        <script src="{% static 'js/main.js' %}"></script> 
        <!--=====================================
                    JS LINK PART END
        =======================================-->
    </body>
</html>

templates/reset-password.html
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="rtl">
    <head>
        <!--=====================================
                    META TAG PART START
        =======================================-->
        <!-- REQUIRE META -->
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <!-- AUTHOR META -->
        <meta name="author" content="mironcoder">
        <meta name="email" content="mironcoder@gmail.com">
        <meta name="profile" content="https://themeforest.net/user/mironcoder">

        <!-- TEMPLATE META -->
        <meta name="name" content="Greeny">
        <meta name="title" content="Greeny - eCommerce HTML Template">
        <meta name="keywords" content="organic, food, shop, ecommerce, store, html, bootstrap, template, agriculture, vegetables, webshop, farm, grocery, natural, online store">
        <!--=====================================
                    META-TAG PART END
        =======================================-->

        <!-- WEBPAGE TITLE -->
        <title>Greeny - Reset Password</title>

        <!--=====================================
                    CSS LINK PART START
        =======================================-->
        <!-- FAVICON -->
        <link rel="icon" href="{{ media_url }}images/favicon.png">

        <!-- FONTS -->
        <link rel="stylesheet" href="{% static 'fonts/flaticon/flaticon.css' %}">
        <link rel="stylesheet" href="{% static 'fonts/icofont/icofont.min.css' %}">
        <link rel="stylesheet" href="{% static 'fonts/fontawesome/fontawesome.min.css' %}">

        <!-- VENDOR -->
        <link rel="stylesheet" href="{% static 'vendor/venobox/venobox.min.css' %}">
        <link rel="stylesheet" href="{% static 'vendor/slickslider/slick.min.css' %}">
        <link rel="stylesheet" href="{% static 'vendor/niceselect/nice-select.min.css' %}">
        <link rel="stylesheet" href="{% static 'vendor/bootstrap/bootstrap.min.css' %}">

        <!-- CUSTOM -->
        <link rel="stylesheet" href="{% static 'css/main.css' %}">
        <link rel="stylesheet" href="{% static 'css/user-auth.css' %}">
        <!--=====================================
                    CSS LINK PART END
        =======================================-->
    </head>
    <body>
        <!--=====================================
                    USER FORM PART START
        =======================================-->
        <section class="user-form-part">
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-12 col-sm-10 col-md-8 col-lg-6 col-xl-5">
                        <div class="user-form-logo">
                            
                        </div>
                        <div class="user-form-card">
                            <div class="user-form-title">
                                <h2>نگران نباشید!</h2>
                                <p>هیچ مشکلی وجود ندارد! تنها مراحل زیر را دنبال کنید.</p>
                            </div>
                            <form class="user-form" action="{% url 'account_shop_project:reset_password' %}" method="post">
                                {% csrf_token %}
                                <div class="form-group">
                                    {{ form.email }}
                                </div>
                                <div class="form-button">
                                    <button type="submit">دریافت لینک فعالسازی</button>
                                </div>
                            </form>
                        </div>
                        <div class="user-form-remind">

                            <p>برگشت به<a href="{% url 'account_shop_project:login' %}"> صفحه ورود</a></p>
                        </div>
                        <div class="user-form-footer">
                            <p>ساخته شده توسط محمد رضا اخلاقی</p>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <!--=====================================
                    USER FORM PART END
        =======================================-->


        <!--=====================================
                    JS LINK PART START
        =======================================-->
        <!-- VENDOR -->
        <script src="{% static 'vendor/bootstrap/jquery-1.12.4.min.js' %}"></script>
        <script src="{% static 'vendor/bootstrap/popper.min.js' %}"></script>
        <script src="{% static 'vendor/bootstrap/bootstrap.min.js' %}"></script>
        <script src="{% static 'vendor/countdown/countdown.min.js' %}"></script>
        <script src="{% static 'vendor/niceselect/nice-select.min.js' %}"></script>
        <script src="{% static 'vendor/slickslider/slick.min.js' %}"></script>
        <script src="{% static 'vendor/venobox/venobox.min.js' %}"></script>

        <!-- CUSTOM -->
        <script src="{% static 'js/nice-select.js' %}"></script>
        <script src="{% static 'js/countdown.js' %}"></script>
        <script src="{% static 'js/accordion.js' %}"></script>
        <script src="{% static 'js/venobox.js' %}"></script>
        <script src="{% static 'js/slick.js' %}"></script>
        <script src="{% static 'js/main.js' %}"></script> 
        <!--=====================================
                    JS LINK PART END
        =======================================-->
    </body>
</html>